### ISSUE TITLE
Create runner HUD

### ISSUE THREAD

**Issue by Planks** [esamarathon/esa-layouts#10]
In time for winter.

Create runnerhud.html layout page

It must be built with a fixed resolution of 800x480 in mind

This page should simply display if there are donations ready to be read in the "read donations" screen

for example

Black background, white text: No donations currently
Red background, white text: Donations pending

If we want to do some more cool stuff on this page we could also show the current timer and how many $ of donations were raised since the last reset. That should encourage the runners to try and get the audience to donate.

**Comment by Planks** [comment]
![4EC059C8-8E7E-454F-B933-FC62E9326F63](https://user-images.githubusercontent.com/16325321/72340333-54a9e180-36c8-11ea-9772-2dc6e61ce8dd.jpeg)

The page shall be displayed on these desktop RPI screens.

**Comment by zoton2** [comment]
Have added a simple page which will indicate if there is donations to be read or not, can size to whatever display resolution. Also have most of a plan to deploy it, although this will mostly happen at the event.
