### ISSUE TITLE
Sticky donation incentives / bid wars in Omnibar

### ISSUE THREAD

**Issue by Edenal** [esamarathon/esa-layouts#48]
https://pbs.twimg.com/media/E5pWxsJWEAEV7Mj?format=jpg&name=large

To push and show progress on incentives or bidwars. Being able to sticky one incentive in the omnibar

**Comment by zoton2** [comment]
As an extra note from a meeting earlier: currently this feature should permanently pin said bid on the omnibar so it never changes, not even other generic messages, until disabled.
