### ISSUE TITLE
Alternate layout depending on crowd size

### ISSUE THREAD

**Issue by Edenal** [esamarathon/esa-layouts#52]
Applicable for the most common layout styles: 
4.3 / 16:9 
4.3 race / 16:9 race

During graveyard blocks there's usually less people in the audience. During these times we may want to increase focus on the runner + couch and hide the empty seats.

**Comment by zoton2** [comment]
Some of this may be covered in #56 now, but will leave open.

**Comment by zoton2** [comment]
Has been done for the relevant layouts in issue #56.
