### ISSUE TITLE
Integrate "mini credits reel"

### ISSUE THREAD

**Issue by zoton2** [esamarathon/esa-layouts#53]
The idea is during the intermissions after a run has finished, we show a list of all the people who have donated (and subs/cheers (if over a certain amount?) if those also go to the charity, which currently is the plan) during that run. We may also want to show the combined total of everything received too if not too low.

Another idea for these credits is to list runners/commentators/volunteers who contributed to the run too, but not sure how to do that currently.

**Comment by Planks** [comment]
When the run timer stops, the credits reel should replace/cover/run inside of the omnibar.

The credits should be a string in the config file with various parameters able to be replaced.

It should support basic markdown (bold, italic, underline)

For example:

Runner: {{name}} --- Commentators: {{name}} --- Donation Reader: {{name}} --- Donation Screeners: preset list of names --- Tech Crew: preset list of names --- Donators: {{names}} --- Subscribers: {{names}} ---  Cheers: {{names}} etc etc etc

**Comment by zoton2** [comment]
Have currently implemented this partially hardcoded, although it will add/remove certain sections if there is no one to show. Donation screeners and tech crew have a configuration option because they will be the same all event. There is also a configuration option for the "header" that appears above the credits.
